import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import matter from "gray-matter";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kushal's Blog Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 mb-6 rounded-md  ">
        <Link href="/">
          <h1 className= "text-2xl text-white font-bold">
            Charmi's Blog
          </h1>
        </Link>
        <p className="text-slate-300">
          Welcome to Charmi's Blog
        </p>
      </div>
    </header>
  ); 

  const footer = (
    <footer>
      <div className="border-t border-slate-400 text-center mt-4 py-2  text-slate-400">
        <p >
          Made by charmi
        </p>
      </div>
    </footer>
  ); 

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl px-2">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
